name: github action demo
on: [push]
jobs:
  Execute-github-workflows-actions:
    runs-on: ubuntu-latest
    steps: 
      - run: echo "The job is running for ${{ github.repository }} repository. "
      - run: echo "The job is running ${{ github.event_name }} event in workflow. "
      - run: echo "The job is running in ${{ runner.os }} Operating system. "
