name: github action sample version test
on: [push]
jobs:
  pull-from-actions:
    runs-on: ubuntu-latest
    steps:
      #- name: "print Repo name"
      - run: echo "Repo is ${{github.repository}} and we are in ${{github.ref}} Branch. "

      #- name: "Take checkout"
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: "14"

      - run: npm install -g bats
      - run: bats -v
