name: github action sample version test
on: [push]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      #- name: "print Repo name"
      - run: echo "Repo is ${{github.repository}} and we are in ${{github.ref}} Branch. "

      - name: "Take checkout"
        uses: actions/checkout@v4

      - name: "Install latest version of node js"
        uses: actions/setup-node@v3
        with:
          node-version: "latest"

      - name: "Install bats a testing framework of node js"
        run: npm install -g bats
      - run: bats -v

      - run: npm install -g @angular/cli
      - run: ng v

      #- name: "checkout the repository"
      #  uses: actions/checkout@v4

      - name: "give sscripts executable permissions "
        run: chmod +x ./script1.sh ./script2.sh

      - name: "run both scripts together"
        run: |
          ./script1.sh
          ./script2.sh

  #job2:
  #  runs-on: [push]

  # steps:
  #  - name: "checkout the repository"
  #   uses: actions/checkout@v4

  #- name: "give sscripts executable permissions "
  # run: chmod +x ./script1.sh ./script2.sh

  # - name: "run both scripts together"
  #  run: |
  #   ./script1.sh
  #  ./script2.sh
